In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from math import e, log, tan
import os
import re

def get_smoothed_pulses(pressure: np.ndarray, window_size: int) -> np.ndarray:
    return np.convolve(pressure, window_size, mode='valid')

#vals_stable = vals[9500:10500]
#vals_smooth = get_smoothed_pulses(vals_stable, 5)

#print(vals_stable.max() - vals_stable.min())

folder_path = 'data/logs'
file_list = os.listdir(folder_path)

#df = pd.DataFrame(['pump_name', 'frequency', 'values', 'smoothed', 'stable'])

i = 0

rows = []

def parse_file(filename):
    parts = filename.split('_')
    pump_name = parts[7] 
    frequency = parts[-2]
    frequency_f = float(frequency.replace(',', '.').replace('г', '').replace('Г', ''))
    values = pd.read_csv('data/logs/' + filename).to_numpy().flatten()
    smoothed = get_smoothed_pulses(values, 10)
    stable = values[(len(smoothed) // 2) - 1000: (len(smoothed) // 2) + 1000]
    amp = stable.max() - stable.min()
    amp_whole = values.max() - values.min()
    mean = stable.mean()
    std_div = np.std(values)
    return [pump_name,frequency_f, values, smoothed, stable, amp, amp_whole, mean, std_div]

for name in file_list:
    row = parse_file(name)
    rows.append(row)

df = pd.DataFrame.from_records(rows)
df.columns = ['pump_name','frequency', 'values', 'smoothed', 'stable', 'amp', 'amp_whole', 'mean', 'std_div']

df.head()

,pump_name,frequency,values,smoothed,stable,amp,amp_whole,mean,std_div
0,Н00182642,0.5,"[99, 307, 99, 315, 99, 309, 99, 313, 99, 318, ...","[990, 3070, 990, 3150, 990, 3090, 990, 3130, 9...","[115, 100, 103, 100, 118, 100, 103, 100, 115, ...",376,999,149.5350,181.961118
1,Н00182642,1.0,"[99, 314, 99, 316, 99, 320, 99, 320, 99, 319, ...","[990, 3140, 990, 3160, 990, 3200, 990, 3200, 9...","[102, 672, 102, 673, 102, 673, 102, 666, 102, ...",999,999,349.9215,292.173840
2,Н00182642,1.5,"[99, 403, 99, 412, 99, 394, 99, 403, 99, 407, ...","[990, 4030, 990, 4120, 990, 3940, 990, 4030, 9...","[109, 947, 109, 938, 109, 923, 109, 917, 109, ...",998,999,314.2540,279.459868
3,Н00182642,2.0,"[99, 488, 99, 482, 99, 488, 99, 485, 99, 490, ...","[990, 4880, 990, 4820, 990, 4880, 990, 4850, 9...","[55, 117, 923, 117, 845, 117, 837, 117, 846, 1...",999,999,308.4175,276.780891
4,Н00182642,3.0,"[99, 788, 99, 784, 99, 795, 99, 788, 99, 788, ...","[990, 7880, 990, 7840, 990, 7950, 990, 7880, 9...","[237, 133, 224, 133, 256, 133, 546, 134, 86, 1...",998,999,318.4870,280.096649